import { describe, expect, it } from "vitest";
import { applyDecision, applyDueVirtualInterest, approveWorkTask, calculateCompletionStreak, calculateFamilySummary, calculateVirtualInterestPayments, createWorkTask, initialFamilyData, isMonthlySettlementDue, recordPocketMoneyPayment, streakRewardFor, submitWorkTask, updateVirtualInterest } from "../lib/family-data";
import { isValidParentPin } from "../lib/parent-pin-rules";
describe("family money calculations", () => {
  it("adds periodic pocket money to the child balance and activity feed", () => { const result = recordPocketMoneyPayment(initialFamilyData, "mia-weekly"); expect(result.members.find((member) => member.id === "mia")?.balance).toBe(332); expect(result.decisions[0]).toMatchObject({ memberId: "mia", type: "income", amount: 12 }); });
  it("tracks saving against a goal without reducing the total saved balance", () => { const result = applyDecision(initialFamilyData, { memberId: "mia", type: "save", amount: 20, title: "Art money", category: "Goal", goalId: "mia-art" }); expect(result.members.find((member) => member.id === "mia")?.balance).toBe(320); expect(result.goals.find((goal) => goal.id === "mia-art")?.saved).toBe(132); });
  it("summarises the children’s saved balance and goal progress", () => { expect(calculateFamilySummary(initialFamilyData)).toMatchObject({ totalSaved: 785, goalSaved: 417, goalTarget: 680, goalProgress: 61 }); });
  it("calculates a different virtual monthly rate for each child", () => { const data = updateVirtualInterest(initialFamilyData, { enabled: true, settlementDay: 5, ratesByMemberId: { mia: 1, theo: 2 } }); expect(calculateVirtualInterestPayments(data)).toEqual([{ memberId: "mia", rate: 1, amount: 3.2 }, { memberId: "theo", rate: 2, amount: 9.3 }]); });
  it("records transparent rate-history entries when a rate changes", () => { const date = new Date("2026-08-03T09:00:00.000Z"); const updated = updateVirtualInterest(initialFamilyData, { enabled: true, settlementDay: 5, ratesByMemberId: { mia: 2, theo: 1 } }, date); expect(updated.virtualInterest.rateHistory).toEqual([expect.objectContaining({ memberId: "mia", previousRate: 1, newRate: 2, changedAt: date.toISOString() })]); });
  it("settles unpaid interest automatically only on or after the chosen day", () => { const configured = updateVirtualInterest(initialFamilyData, { enabled: true, settlementDay: 5, ratesByMemberId: { mia: 1, theo: 2 } }); expect(isMonthlySettlementDue(configured, new Date("2026-08-04T09:00:00.000Z"))).toBe(false); const settled = applyDueVirtualInterest(configured, new Date("2026-08-05T09:00:00.000Z")); expect(settled.members.find((member) => member.id === "theo")?.balance).toBe(474.3); expect(isMonthlySettlementDue(settled, new Date("2026-08-26T09:00:00.000Z"))).toBe(false); });
  it("pays a streak bonus after three consecutive completion days", () => { const withHistory = { ...initialFamilyData, workTasks: [{ id: "a", memberId: "mia", title: "Day one", description: "", amount: 1, status: "approved" as const, createdAt: "2026-08-01T09:00:00.000Z", completedAt: "2026-08-01T09:00:00.000Z" }, { id: "b", memberId: "mia", title: "Day two", description: "", amount: 1, status: "approved" as const, createdAt: "2026-08-02T09:00:00.000Z", completedAt: "2026-08-02T09:00:00.000Z" }] }; const created = createWorkTask(withHistory, { memberId: "mia", title: "Day three", description: "", amount: 3 }, new Date("2026-08-03T08:00:00.000Z")); const submitted = submitWorkTask(created, created.workTasks[0].id, new Date("2026-08-03T17:00:00.000Z")); const approved = approveWorkTask(submitted, submitted.workTasks[0].id, new Date("2026-08-03T18:00:00.000Z")); expect(calculateCompletionStreak(approved.workTasks, "mia", new Date("2026-08-03T18:00:00.000Z"))).toBe(3); expect(approved.workTasks[0].rewardAmount).toBe(2); expect(approved.members.find((member) => member.id === "mia")?.balance).toBe(325); expect(approved.decisions.slice(0, 2)).toEqual(expect.arrayContaining([expect.objectContaining({ category: "Streak reward", amount: 2 }), expect.objectContaining({ category: "Work task", amount: 3 })])); });
  it("uses a bonus every third completion day and validates four-digit parent PINs", () => { expect(streakRewardFor(2)).toBe(0); expect(streakRewardFor(3)).toBe(2); expect(streakRewardFor(6)).toBe(2); expect(isValidParentPin("2468")).toBe(true); expect(isValidParentPin("12")).toBe(false); expect(isValidParentPin("abcd")).toBe(false); });
});
