import { Platform, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { ScreenContainer } from "@/components/screen-container";

const Step = ({ number, icon, children }: { number: string; icon: keyof typeof MaterialIcons.glyphMap; children: string }) => <View style={styles.step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{number}</Text></View><View style={styles.stepIcon}><MaterialIcons name={icon} size={19} color="#176B73" /></View><Text style={styles.stepText}>{children}</Text></View>;

export default function InstallScreen() {
  const onWeb = Platform.OS === "web";
  return <ScreenContainer><View style={styles.content}><View style={styles.heroIcon}><MaterialIcons name="add-to-home-screen" size={32} color="#176B73" /></View><Text style={styles.eyebrow}>IOS WITHOUT THE APP STORE</Text><Text style={styles.title}>Install Family Money.</Text><Text style={styles.subtitle}>Use Safari to add this app to your iPhone or iPad home screen. It opens like an app, keeps your local family record on the device, and does not need an Apple Developer Account.</Text><View style={styles.card}><Text style={styles.cardTitle}>On iPhone or iPad</Text><Step number="1" icon="ios-share">Open this Family Money link in Safari.</Step><Step number="2" icon="ios-share">Tap the Share button at the bottom of Safari.</Step><Step number="3" icon="add-box">Choose “Add to Home Screen”, then tap Add.</Step></View><View style={styles.note}><MaterialIcons name="info-outline" size={19} color="#5E4A78" /><Text style={styles.noteText}>{onWeb ? "You are using the web version. For the best iOS experience, complete the steps above in Safari." : "This guide is for the iOS web version. Your Android app can continue to use the native version."}</Text></View></View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { flex: 1, padding: 22, paddingTop: 28 }, heroIcon: { width: 62, height: 62, alignItems: "center", justifyContent: "center", borderRadius: 21, backgroundColor: "#E4F1F0" }, eyebrow: { color: "#176B73", fontSize: 10, letterSpacing: 1.25, fontWeight: "800", marginTop: 19 }, title: { color: "#1D2C3A", fontSize: 29, fontWeight: "800", marginTop: 4 }, subtitle: { color: "#65737C", fontSize: 13, lineHeight: 20, marginTop: 7 }, card: { backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E6E4DD", borderRadius: 22, padding: 17, marginTop: 23, gap: 15 }, cardTitle: { color: "#1D2C3A", fontSize: 16, fontWeight: "800" }, step: { flexDirection: "row", alignItems: "flex-start", gap: 10 }, stepNumber: { width: 23, height: 23, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#176B73", marginTop: 1 }, stepNumberText: { color: "#FFFFFF", fontSize: 11, fontWeight: "900" }, stepIcon: { width: 29, height: 29, alignItems: "center", justifyContent: "center", borderRadius: 10, backgroundColor: "#E4F1F0" }, stepText: { color: "#42525C", fontSize: 13, lineHeight: 19, flex: 1, paddingTop: 4 }, note: { flexDirection: "row", alignItems: "flex-start", gap: 10, backgroundColor: "#F1ECFA", borderRadius: 17, padding: 14, marginTop: 17 }, noteText: { color: "#5E4A78", fontSize: 12, lineHeight: 18, flex: 1 } });
