import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useFamily } from "@/components/family-provider";
import { childMembers, currencySymbol } from "@/lib/family-data";
import { haptic } from "@/lib/haptics";

export default function NewWorkTaskScreen() {
  const router = useRouter(); const { data, createWork } = useFamily(); const children = childMembers(data); const [memberId, setMemberId] = useState(children[0]?.id); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [amount, setAmount] = useState("");
  const create = () => { const value = Number(amount.replace(",", ".")); if (!memberId || !title.trim() || !Number.isFinite(value) || value <= 0) return Alert.alert("Add the work details", "Choose a child, give the job a name, and enter a positive Hong Kong dollar income amount."); createWork({ memberId, title, description, amount: value }); haptic.success(); router.back(); };
  return <KeyboardAvoidingView style={styles.root} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><View style={styles.topBar}><TouchableOpacity activeOpacity={0.75} onPress={() => router.back()}><Text style={styles.cancel}>Cancel</Text></TouchableOpacity><Text style={styles.topTitle}>New work task</Text><View style={{ width: 48 }} /></View><Text style={styles.eyebrow}>PRACTISE EARNING</Text><Text style={styles.title}>Offer a small job.</Text><Text style={styles.subtitle}>Describe what “done” looks like and agree the amount before the work begins.</Text><Text style={styles.label}>WHO IS THIS FOR?</Text><View style={styles.memberChoices}>{children.map((child) => <TouchableOpacity key={child.id} style={[styles.memberChoice, memberId === child.id && styles.memberSelected]} activeOpacity={0.76} onPress={() => { haptic.selection(); setMemberId(child.id); }}><View style={[styles.dot, { backgroundColor: child.color }]} /><Text style={[styles.memberText, memberId === child.id && styles.memberTextSelected]}>{child.name}</Text></TouchableOpacity>)}</View><Text style={styles.label}>WORK TASK</Text><TextInput value={title} onChangeText={setTitle} placeholder="e.g. Sort the recycling" placeholderTextColor="#9AA3A8" style={styles.field} returnKeyType="done" /><Text style={styles.label}>WHAT DOES DONE LOOK LIKE? <Text style={styles.optional}>OPTIONAL</Text></Text><TextInput value={description} onChangeText={setDescription} placeholder="e.g. Put each kind into the right bin" placeholderTextColor="#9AA3A8" style={[styles.field, styles.description]} multiline /><Text style={styles.label}>INCOME WHEN APPROVED (HKD)</Text><View style={styles.amountField}><Text style={styles.currency}>{currencySymbol}</Text><TextInput value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder="0" placeholderTextColor="#A3ABB0" style={styles.amountInput} accessibilityLabel="Work income in Hong Kong dollars" /></View><TouchableOpacity style={styles.createButton} activeOpacity={0.85} onPress={create}><MaterialIcons name="add-task" size={20} color="#FFFFFF" /><Text style={styles.createText}>Create work task</Text></TouchableOpacity></ScrollView></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: "#F7F6F2" }, content: { padding: 20, paddingTop: 17, paddingBottom: 34 }, topBar: { alignItems: "center", justifyContent: "space-between", flexDirection: "row", marginBottom: 27 }, cancel: { color: "#6C4A9B", fontSize: 15, fontWeight: "800" }, topTitle: { color: "#1D2C3A", fontSize: 15, fontWeight: "800" }, eyebrow: { color: "#6C4A9B", fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, title: { color: "#1D2C3A", fontSize: 28, fontWeight: "800", marginTop: 4 }, subtitle: { color: "#65737C", fontSize: 13, lineHeight: 19, marginTop: 6 }, label: { color: "#6B777D", fontSize: 10, letterSpacing: 0.9, fontWeight: "900", marginBottom: 9, marginTop: 20 }, optional: { color: "#9AA3A8", fontSize: 9 }, memberChoices: { flexDirection: "row", gap: 10 }, memberChoice: { flex: 1, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7, minHeight: 44, backgroundColor: "#FFFFFF", borderColor: "#E5E4DF", borderWidth: 1, borderRadius: 14 }, memberSelected: { backgroundColor: "#F1ECFA", borderColor: "#6C4A9B" }, dot: { width: 9, height: 9, borderRadius: 5 }, memberText: { color: "#65737C", fontSize: 14, fontWeight: "800" }, memberTextSelected: { color: "#6C4A9B" }, field: { borderRadius: 15, backgroundColor: "#FFFFFF", borderColor: "#E1E1DC", borderWidth: 1, color: "#1D2C3A", fontSize: 14, paddingHorizontal: 14, paddingVertical: 14 }, description: { minHeight: 86, textAlignVertical: "top" }, amountField: { alignItems: "center", flexDirection: "row", borderRadius: 17, backgroundColor: "#FFFFFF", borderColor: "#E1E1DC", borderWidth: 1, paddingHorizontal: 16 }, currency: { color: "#6C4A9B", fontSize: 20, fontWeight: "800", marginRight: 5 }, amountInput: { flex: 1, color: "#1D2C3A", fontSize: 29, fontWeight: "800", paddingVertical: 14 }, createButton: { minHeight: 54, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, borderRadius: 18, backgroundColor: "#6C4A9B", marginTop: 28 }, createText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" } });

