import { Alert, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useFamily } from "@/components/family-provider";
import { ScreenContainer } from "@/components/screen-container";
import { childMembers, formatCurrency, formatShortDate } from "@/lib/family-data";
import { haptic } from "@/lib/haptics";

export default function PocketMoneyScreen() { const router = useRouter(); const { data, recordPocketMoney } = useFamily(); const children = childMembers(data); const confirmPayment = (ruleId: string, childName: string, amount: number) => Alert.alert("Record pocket money?", `Add ${formatCurrency(amount)} to ${childName}’s saved balance and activity history?`, [{ text: "Not now", style: "cancel" }, { text: "Record payment", onPress: () => { recordPocketMoney(ruleId); haptic.success(); } }]); return <ScreenContainer><FlatList data={data.pocketMoneyRules} keyExtractor={(rule) => rule.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>A CONSISTENT ROUTINE</Text><Text style={styles.title}>Pocket money</Text><Text style={styles.subtitle}>Record the periodic income you’ve agreed with each child.</Text><View style={styles.tip}><MaterialIcons name="tips-and-updates" size={20} color="#176B73" /><Text style={styles.tipText}>Showing payments is a simple way to make the family record feel trustworthy.</Text></View></View>} renderItem={({ item }) => { const child = children.find((member) => member.id === item.memberId); return <View style={styles.ruleCard}><View style={styles.ruleTop}><View style={[styles.ruleAvatar, { backgroundColor: child?.color ?? "#176B73" }]}><Text style={styles.ruleAvatarText}>{child?.name[0] ?? "F"}</Text></View><View style={styles.ruleCopy}><Text style={styles.ruleName}>{child?.name ?? "Family member"}</Text><Text style={styles.ruleCadence}>{item.cadence} pocket money</Text></View><Text style={styles.ruleAmount}>{formatCurrency(item.amount)}</Text></View><View style={styles.ruleDivider} /><View style={styles.ruleBottom}><View><Text style={styles.nextLabel}>NEXT EXPECTED</Text><Text style={styles.nextDate}>{formatShortDate(item.nextPayment)}</Text></View><TouchableOpacity style={styles.recordButton} activeOpacity={0.78} onPress={() => confirmPayment(item.id, child?.name ?? "Family member", item.amount)}><Text style={styles.recordButtonText}>Record payment</Text></TouchableOpacity></View></View>; }} ItemSeparatorComponent={() => <View style={{ height: 14 }} />} ListFooterComponent={<TouchableOpacity style={styles.reviewLink} activeOpacity={0.75} onPress={() => router.push("/(tabs)/activity")}><MaterialIcons name="history" size={19} color="#176B73" /><Text style={styles.reviewText}>See all recorded income</Text><MaterialIcons name="chevron-right" size={21} color="#176B73" /></TouchableOpacity>} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 14, paddingBottom: 30 }, header: { gap: 7, marginBottom: 19 }, eyebrow: { color: "#176B73", fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, title: { color: "#1D2C3A", fontSize: 28, fontWeight: "800" }, subtitle: { color: "#65737C", fontSize: 13, lineHeight: 18 }, tip: { flexDirection: "row", gap: 10, borderRadius: 17, backgroundColor: "#E4F1F0", padding: 14, marginTop: 9 }, tipText: { color: "#3D6265", fontSize: 12, lineHeight: 17, flex: 1 }, ruleCard: { backgroundColor: "#FFFFFF", borderColor: "#E6E4DD", borderRadius: 22, borderWidth: 1, padding: 17, gap: 16 }, ruleTop: { flexDirection: "row", alignItems: "center", gap: 11 }, ruleAvatar: { width: 41, height: 41, alignItems: "center", justifyContent: "center", borderRadius: 14 }, ruleAvatarText: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" }, ruleCopy: { flex: 1 }, ruleName: { color: "#1D2C3A", fontSize: 16, fontWeight: "800" }, ruleCadence: { color: "#758188", fontSize: 12, marginTop: 3 }, ruleAmount: { color: "#176B73", fontSize: 20, fontWeight: "900" }, ruleDivider: { height: 1, backgroundColor: "#EEEDE8" }, ruleBottom: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, nextLabel: { color: "#8A959B", fontSize: 9, letterSpacing: 0.7, fontWeight: "800" }, nextDate: { color: "#40505B", fontSize: 13, fontWeight: "800", marginTop: 4 }, recordButton: { minHeight: 39, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: "#176B73", paddingHorizontal: 13 }, recordButtonText: { color: "#FFFFFF", fontSize: 12, fontWeight: "800" }, reviewLink: { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, borderRadius: 17, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E6E4DD", paddingVertical: 14, marginTop: 17 }, reviewText: { color: "#176B73", fontSize: 13, fontWeight: "800" } });
