import { Alert, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useFamily } from "@/components/family-provider";
import { ScreenContainer } from "@/components/screen-container";
import { childMembers } from "@/lib/family-data";
import { haptic } from "@/lib/haptics";

export default function SettingsScreen() { const router = useRouter(); const { data, resetFamily } = useFamily(); const children = childMembers(data); const parents = data.members.filter((member) => member.role === "parent"); const reset = () => Alert.alert("Reset this device’s family data?", "This removes locally recorded choices and returns the example family record. This cannot be undone.", [{ text: "Keep my data", style: "cancel" }, { text: "Reset local data", style: "destructive", onPress: () => { resetFamily(); haptic.success(); router.back(); } }]); const person = (member: typeof data.members[number], role: string) => <View style={styles.personRow} key={member.id}><View style={[styles.avatar, { backgroundColor: member.color }]}><Text style={styles.avatarText}>{member.name[0]}</Text></View><Text style={styles.personName}>{member.name}</Text><Text style={styles.role}>{role}</Text></View>; return <ScreenContainer><View style={styles.content}><Text style={styles.eyebrow}>ON THIS DEVICE</Text><Text style={styles.title}>Your family</Text><Text style={styles.subtitle}>Parents oversee the record and talk through choices with children.</Text><View style={styles.card}><Text style={styles.cardLabel}>PARENTS</Text>{parents.map((member, index) => <View key={member.id}>{person(member, "Parent")}{index < parents.length - 1 && <View style={styles.divider} />}</View>)}<View style={styles.sectionDivider} /><Text style={styles.cardLabel}>CHILDREN</Text>{children.map((member, index) => <View key={member.id}>{person(member, "Child")}{index < children.length - 1 && <View style={styles.divider} />}</View>)}</View><View style={styles.privacy}><MaterialIcons name="devices" size={19} color="#526068" /><Text style={styles.privacyText}>Family Money Tracker currently keeps this data in private local storage on this phone. It does not create an online account.</Text></View><TouchableOpacity style={styles.resetButton} activeOpacity={0.75} onPress={reset}><MaterialIcons name="restart-alt" size={19} color="#B44733" /><Text style={styles.resetText}>Reset local family data</Text></TouchableOpacity></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, padding: 20, paddingTop: 16 }, eyebrow: { color: "#176B73", fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, title: { color: "#1D2C3A", fontSize: 28, fontWeight: "800", marginTop: 3 }, subtitle: { color: "#65737C", fontSize: 13, lineHeight: 19, marginTop: 6 }, card: { marginTop: 22, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E6E4DD", borderRadius: 22, padding: 16, gap: 12 }, cardLabel: { color: "#8A959B", fontSize: 10, letterSpacing: 0.9, fontWeight: "900" }, personRow: { flexDirection: "row", alignItems: "center", gap: 10 }, avatar: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" }, personName: { color: "#263640", fontSize: 14, fontWeight: "800", flex: 1 }, role: { color: "#78848B", fontSize: 12 }, divider: { height: 1, backgroundColor: "#F0EFEB", marginLeft: 44, marginTop: 12 }, sectionDivider: { height: 1, backgroundColor: "#E4E3DE", marginVertical: 3 }, privacy: { flexDirection: "row", alignItems: "flex-start", gap: 10, borderRadius: 17, backgroundColor: "#EEEFEA", padding: 14, marginTop: 18 }, privacyText: { flex: 1, color: "#58666D", fontSize: 12, lineHeight: 18 }, resetButton: { alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 7, borderRadius: 15, backgroundColor: "#FCEBE7", paddingVertical: 14, marginTop: 18 }, resetText: { color: "#B44733", fontSize: 13, fontWeight: "800" } });
