import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { applyDecision, applyDueVirtualInterest, approveWorkTask, createWorkTask, initialFamilyData, recordPocketMoneyPayment, submitWorkTask, updateVirtualInterest, type FamilyData, type RecordDecisionInput, type VirtualInterestInput, type WorkTask } from "@/lib/family-data";

const STORAGE_KEY = "family-money-tracker-v1";
interface FamilyContextValue { data: FamilyData; isReady: boolean; recordDecision: (input: RecordDecisionInput) => void; recordPocketMoney: (ruleId: string) => void; saveVirtualInterest: (settings: VirtualInterestInput) => void; submitWork: (taskId: string) => void; createWork: (input: Pick<WorkTask, "memberId" | "title" | "description" | "amount">) => void; approveWork: (taskId: string) => void; resetFamily: () => void; }
const FamilyContext = createContext<FamilyContextValue | undefined>(undefined);
export function FamilyProvider({ children }: { children: ReactNode }) { const [data, setData] = useState<FamilyData>(initialFamilyData); const [isReady, setIsReady] = useState(false);
  useEffect(() => { const hydrate = async () => { try { const stored = await AsyncStorage.getItem(STORAGE_KEY); if (stored) { const parsed = JSON.parse(stored) as Partial<FamilyData>; const oldInterest = parsed.virtualInterest as Partial<FamilyData["virtualInterest"]> & { monthlyRate?: number }; const legacyRate = oldInterest?.monthlyRate ?? 1; const ratesByMemberId = Object.fromEntries(initialFamilyData.members.filter((member) => member.role === "child").map((member) => [member.id, oldInterest?.ratesByMemberId?.[member.id] ?? legacyRate])); setData({ ...initialFamilyData, ...parsed, workTasks: parsed.workTasks ?? initialFamilyData.workTasks, virtualInterest: { enabled: oldInterest?.enabled ?? true, ratesByMemberId, settlementDay: oldInterest?.settlementDay ?? 1, lastAppliedMonth: oldInterest?.lastAppliedMonth, rateHistory: oldInterest?.rateHistory ?? [] } }); } } finally { setIsReady(true); } }; void hydrate(); }, []);
  useEffect(() => { if (isReady) setData((current) => applyDueVirtualInterest(current)); }, [isReady]); useEffect(() => { if (isReady) void AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }, [data, isReady]);
  const recordDecision = useCallback((input: RecordDecisionInput) => setData((current) => applyDecision(current, input)), []); const recordPocketMoney = useCallback((ruleId: string) => setData((current) => recordPocketMoneyPayment(current, ruleId)), []); const saveVirtualInterest = useCallback((settings: VirtualInterestInput) => setData((current) => applyDueVirtualInterest(updateVirtualInterest(current, settings))), []); const createWork = useCallback((input: Pick<WorkTask, "memberId" | "title" | "description" | "amount">) => setData((current) => createWorkTask(current, input)), []); const submitWork = useCallback((taskId: string) => setData((current) => submitWorkTask(current, taskId)), []); const approveWork = useCallback((taskId: string) => setData((current) => approveWorkTask(current, taskId)), []); const resetFamily = useCallback(() => setData(initialFamilyData), []);
  const value = useMemo(() => ({ data, isReady, recordDecision, recordPocketMoney, saveVirtualInterest, createWork, submitWork, approveWork, resetFamily }), [data, isReady, recordDecision, recordPocketMoney, saveVirtualInterest, createWork, submitWork, approveWork, resetFamily]); return <FamilyContext.Provider value={value}>{children}</FamilyContext.Provider>; }
export function useFamily() { const context = useContext(FamilyContext); if (!context) throw new Error("useFamily must be used inside FamilyProvider"); return context; }
