import { Alert, Modal, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { useEffect, useState } from "react";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { hasParentPin, isValidParentPin, saveParentPin, verifyParentPin } from "@/lib/parent-pin";
import { haptic } from "@/lib/haptics";

interface ParentPinGateProps { visible: boolean; title: string; onClose: () => void; onVerified: () => void; }
export function ParentPinGate({ visible, title, onClose, onVerified }: ParentPinGateProps) {
  const [setup, setSetup] = useState(false); const [pin, setPin] = useState(""); const [confirm, setConfirm] = useState("");
  useEffect(() => { if (!visible) return; setPin(""); setConfirm(""); void hasParentPin().then((exists) => setSetup(!exists)); }, [visible]);
  const submit = async () => {
    if (!isValidParentPin(pin)) { Alert.alert("Use four digits", "Choose or enter a four-digit parent PIN."); return; }
    if (setup) { if (pin !== confirm) { Alert.alert("PINs do not match", "Enter the same four digits again to confirm."); return; } await saveParentPin(pin); haptic.success(); onVerified(); return; }
    if (await verifyParentPin(pin)) { haptic.success(); onVerified(); } else { haptic.light(); Alert.alert("PIN not recognised", "Try the four-digit parent PIN again."); setPin(""); }
  };
  return <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.handle} /><View style={styles.icon}><MaterialIcons name="lock" size={23} color="#176B73" /></View><Text style={styles.title}>{setup ? "Create a parent PIN" : "Parent approval"}</Text><Text style={styles.text}>{setup ? "Create a four-digit PIN. It is stored securely on this device and protects parent actions." : `Enter your four-digit PIN to ${title.toLowerCase()}.`}</Text><TextInput value={pin} onChangeText={setPin} keyboardType="number-pad" secureTextEntry maxLength={4} style={styles.input} placeholder="••••" placeholderTextColor="#A0A9AC" accessibilityLabel="Parent PIN" autoFocus />{setup && <TextInput value={confirm} onChangeText={setConfirm} keyboardType="number-pad" secureTextEntry maxLength={4} style={styles.input} placeholder="Confirm PIN" placeholderTextColor="#A0A9AC" accessibilityLabel="Confirm parent PIN" />}<TouchableOpacity activeOpacity={0.82} style={styles.confirm} onPress={() => void submit()}><Text style={styles.confirmText}>{setup ? "Create & continue" : "Verify & continue"}</Text></TouchableOpacity><TouchableOpacity activeOpacity={0.72} style={styles.cancel} onPress={onClose}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity></View></View></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: "flex-end", backgroundColor: "rgba(29,44,58,0.32)" }, sheet: { backgroundColor: "#F7F6F2", borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 22, paddingBottom: 35, alignItems: "center" }, handle: { width: 38, height: 4, borderRadius: 2, backgroundColor: "#CBD0CC", marginBottom: 20 }, icon: { width: 44, height: 44, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#E4F1F0" }, title: { color: "#1D2C3A", fontSize: 20, fontWeight: "800", marginTop: 12 }, text: { color: "#65737C", textAlign: "center", fontSize: 13, lineHeight: 19, marginTop: 6, maxWidth: 300 }, input: { width: "100%", backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E1E1DC", borderRadius: 15, color: "#1D2C3A", fontSize: 25, fontWeight: "800", textAlign: "center", letterSpacing: 8, paddingVertical: 12, marginTop: 16 }, confirm: { width: "100%", minHeight: 51, alignItems: "center", justifyContent: "center", backgroundColor: "#176B73", borderRadius: 16, marginTop: 16 }, confirmText: { color: "#FFFFFF", fontSize: 15, fontWeight: "800" }, cancel: { paddingVertical: 14 }, cancelText: { color: "#65737C", fontSize: 14, fontWeight: "800" } });
