import { useMemo, useState } from "react";
import { Alert, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useFamily } from "@/components/family-provider";
import { ScreenContainer } from "@/components/screen-container";
import { childMembers, decisionMeta, formatCurrency, formatShortDate, type MoneyDecisionType } from "@/lib/family-data";
import { haptic } from "@/lib/haptics";

type ActivityFilter = "all" | MoneyDecisionType;
export default function ActivityScreen() {
  const router = useRouter(); const { data, isReady } = useFamily(); const [filter, setFilter] = useState<ActivityFilter>("all"); const children = childMembers(data); const entries = useMemo(() => data.decisions.filter((decision) => filter === "all" || decision.type === filter), [data.decisions, filter]);
  const choice = (value: ActivityFilter, label: string) => { const active = filter === value; return <TouchableOpacity key={value} activeOpacity={0.76} style={[styles.filter, active && styles.filterActive]} onPress={() => { haptic.selection(); setFilter(value); }}><Text style={[styles.filterText, active && styles.filterTextActive]}>{label}</Text></TouchableOpacity>; };
  return <ScreenContainer><FlatList data={isReady ? entries : []} keyExtractor={(item) => item.id} contentContainerStyle={styles.listContent} showsVerticalScrollIndicator={false} ListHeaderComponent={<View style={styles.header}><View style={styles.headerRow}><View><Text style={styles.eyebrow}>THE CONVERSATION</Text><Text style={styles.title}>Money activity</Text><Text style={styles.subtitle}>Choices made together are easier to understand.</Text></View><TouchableOpacity style={styles.addButton} activeOpacity={0.78} onPress={() => { haptic.light(); router.push("/add-decision"); }}><MaterialIcons name="add" size={22} color="#FFFFFF" /></TouchableOpacity></View><View style={styles.filters}>{choice("all", "All")}{choice("income", "Income")}{choice("spend", "Spent")}{choice("save", "Saved")}{choice("invest", "Invested")}</View></View>} renderItem={({ item }) => { const member = children.find((child) => child.id === item.memberId); const meta = decisionMeta[item.type]; const sign = item.type === "spend" ? "−" : item.type === "income" ? "+" : ""; return <TouchableOpacity activeOpacity={0.74} style={styles.row} onPress={() => Alert.alert(item.title, `${member?.name ?? "Family member"} · ${item.category}\n${formatShortDate(item.date)}\n${item.reviewStatus === "reviewed" ? "Reviewed together" : "Talk about this choice together"}`)}><View style={[styles.icon, { backgroundColor: meta.softColor }]}><MaterialIcons name={meta.icon as never} size={20} color={meta.color} /></View><View style={styles.rowCopy}><View style={styles.rowTitleLine}><Text style={styles.rowTitle}>{item.title}</Text>{item.reviewStatus === "discuss" && <View style={styles.discussChip}><Text style={styles.discussText}>DISCUSS</Text></View>}</View><Text style={styles.rowMeta}>{member?.name ?? "Family"} · {item.category} · {formatShortDate(item.date)}</Text></View><Text style={[styles.rowAmount, { color: meta.color }]}>{sign}{formatCurrency(item.amount)}</Text></TouchableOpacity>; }} ItemSeparatorComponent={() => <View style={styles.separator} />} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="receipt-long" size={32} color="#9AA4A9" /><Text style={styles.emptyTitle}>No matching choices yet</Text><Text style={styles.emptyText}>Record a money choice to start a helpful family history.</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ listContent: { paddingBottom: 28 }, header: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 18, gap: 18 }, headerRow: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" }, eyebrow: { color: "#176B73", fontSize: 11, fontWeight: "800", letterSpacing: 1.3 }, title: { color: "#1D2C3A", fontSize: 28, fontWeight: "800", marginTop: 3 }, subtitle: { color: "#65737C", fontSize: 13, lineHeight: 18, marginTop: 4, maxWidth: 265 }, addButton: { width: 43, height: 43, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#176B73", marginTop: 3 }, filters: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, filter: { borderWidth: 1, borderColor: "#E3E2DD", borderRadius: 18, backgroundColor: "#FFFFFF", paddingHorizontal: 12, paddingVertical: 8 }, filterActive: { borderColor: "#176B73", backgroundColor: "#E4F1F0" }, filterText: { color: "#65737C", fontSize: 12, fontWeight: "800" }, filterTextActive: { color: "#176B73" }, row: { flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 20, paddingVertical: 14, backgroundColor: "#F7F6F2" }, icon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, rowCopy: { flex: 1, gap: 4 }, rowTitleLine: { flexDirection: "row", alignItems: "center", gap: 7 }, rowTitle: { color: "#1D2C3A", fontSize: 14, fontWeight: "800", flexShrink: 1 }, rowMeta: { color: "#7B858B", fontSize: 11, lineHeight: 16 }, rowAmount: { fontSize: 14, fontWeight: "800" }, discussChip: { paddingHorizontal: 6, paddingVertical: 3, borderRadius: 6, backgroundColor: "#FFF0D9" }, discussText: { color: "#A35E00", fontSize: 8, letterSpacing: 0.6, fontWeight: "900" }, separator: { height: 1, backgroundColor: "#E9E7E2", marginLeft: 74 }, empty: { alignItems: "center", paddingHorizontal: 40, paddingTop: 54, gap: 9 }, emptyTitle: { color: "#33434E", fontSize: 16, fontWeight: "800", marginTop: 5 }, emptyText: { color: "#748088", fontSize: 13, lineHeight: 19, textAlign: "center" } });
