import { FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { useFamily } from "@/components/family-provider";
import { ScreenContainer } from "@/components/screen-container";
import { childMembers, formatCurrency, formatShortDate } from "@/lib/family-data";
import { haptic } from "@/lib/haptics";

export default function GoalsScreen() {
  const router = useRouter(); const { data } = useFamily(); const children = childMembers(data);
  return <ScreenContainer><FlatList data={data.goals} keyExtractor={(goal) => goal.id} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<View style={styles.header}><Text style={styles.eyebrow}>PUTTING PURPOSE TO MONEY</Text><Text style={styles.title}>Saving goals</Text><Text style={styles.subtitle}>Little choices add up when a goal feels real.</Text><View style={styles.summary}><View style={styles.summaryIcon}><MaterialIcons name="savings" size={23} color="#2C8C6A" /></View><View><Text style={styles.summaryTitle}>Two goals in progress</Text><Text style={styles.summaryText}>Celebrate consistency, not just the finish line.</Text></View></View></View>} renderItem={({ item }) => { const child = children.find((member) => member.id === item.memberId); const percent = Math.round((item.saved / item.target) * 100); return <View style={styles.goalCard}><View style={styles.goalHeader}><View style={[styles.goalAvatar, { backgroundColor: child?.color ?? "#176B73" }]}><Text style={styles.goalAvatarText}>{child?.name[0] ?? "F"}</Text></View><View style={styles.goalHeadCopy}><Text style={styles.goalTitle}>{item.title}</Text><Text style={styles.goalOwner}>{child?.name ?? "Family"} · target {formatShortDate(item.deadline)}</Text></View><Text style={styles.percent}>{percent}%</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${percent}%`, backgroundColor: child?.color ?? "#176B73" }]} /></View><View style={styles.goalFooter}><Text style={styles.saved}>{formatCurrency(item.saved)} <Text style={styles.savedMuted}>of {formatCurrency(item.target)}</Text></Text><TouchableOpacity activeOpacity={0.76} style={styles.addSaving} onPress={() => { haptic.light(); router.push({ pathname: "/add-decision", params: { memberId: item.memberId, type: "save", goalId: item.id } }); }}><MaterialIcons name="add" size={18} color="#176B73" /><Text style={styles.addSavingText}>Add savings</Text></TouchableOpacity></View></View>; }} ItemSeparatorComponent={() => <View style={{ height: 14 }} />} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingTop: 14, paddingBottom: 28 }, header: { gap: 7, marginBottom: 18 }, eyebrow: { color: "#176B73", fontSize: 10, letterSpacing: 1.2, fontWeight: "800" }, title: { color: "#1D2C3A", fontSize: 28, fontWeight: "800" }, subtitle: { color: "#65737C", fontSize: 13, lineHeight: 18 }, summary: { alignItems: "center", flexDirection: "row", gap: 12, borderRadius: 19, backgroundColor: "#E6F4ED", padding: 15, marginTop: 8 }, summaryIcon: { width: 39, height: 39, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#FFFFFF" }, summaryTitle: { color: "#225E49", fontSize: 14, fontWeight: "800" }, summaryText: { color: "#407360", fontSize: 12, marginTop: 3 }, goalCard: { backgroundColor: "#FFFFFF", borderColor: "#E6E4DD", borderRadius: 22, borderWidth: 1, padding: 17, gap: 16 }, goalHeader: { flexDirection: "row", alignItems: "center", gap: 10 }, goalAvatar: { width: 37, height: 37, alignItems: "center", justifyContent: "center", borderRadius: 13 }, goalAvatarText: { color: "#FFFFFF", fontWeight: "800", fontSize: 16 }, goalHeadCopy: { flex: 1 }, goalTitle: { color: "#1D2C3A", fontSize: 16, fontWeight: "800" }, goalOwner: { color: "#78848B", fontSize: 11, marginTop: 3 }, percent: { color: "#176B73", fontSize: 16, fontWeight: "900" }, track: { height: 10, borderRadius: 7, backgroundColor: "#EFF0EC", overflow: "hidden" }, fill: { height: 10, borderRadius: 7 }, goalFooter: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, saved: { color: "#1D2C3A", fontSize: 14, fontWeight: "800" }, savedMuted: { color: "#7B858B", fontWeight: "600" }, addSaving: { flexDirection: "row", alignItems: "center", gap: 4, borderRadius: 12, backgroundColor: "#E4F1F0", paddingHorizontal: 10, paddingVertical: 8 }, addSavingText: { color: "#176B73", fontSize: 12, fontWeight: "800" } });
