import { Platform, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
type Destination = "/pocket-money" | "/virtual-interest" | "/work" | "/install" | "/settings";
export default function MoreScreen() { const router = useRouter(); const open = (path: Destination) => { haptic.light(); router.push(path); }; const item = (icon: keyof typeof MaterialIcons.glyphMap, color: string, background: string, title: string, detail: string, path: Destination) => <TouchableOpacity key={path} style={styles.item} activeOpacity={0.75} onPress={() => open(path)}><View style={[styles.itemIcon, { backgroundColor: background }]}><MaterialIcons name={icon} size={21} color={color} /></View><View style={styles.itemCopy}><Text style={styles.itemTitle}>{title}</Text><Text style={styles.itemText}>{detail}</Text></View><MaterialIcons name="chevron-right" size={24} color="#89949A" /></TouchableOpacity>; return <ScreenContainer><View style={styles.content}><Text style={styles.eyebrow}>FAMILY SPACE</Text><Text style={styles.title}>A few helpful tools.</Text><Text style={styles.subtitle}>Keep the routine clear, and keep the conversation kind.</Text><View style={styles.group}>{item("event-repeat", "#176B73", "#E4F1F0", "Pocket money", "Review weekly income and record payments.", "/pocket-money")}<View style={styles.itemDivider} />{item("auto-graph", "#9A6B18", "#FFF1D7", "Virtual interest", "Set rates, see the history and explain the maths.", "/virtual-interest")}<View style={styles.itemDivider} />{item("assignment-turned-in", "#6C4A9B", "#F1ECFA", "Work & income", "Create jobs, celebrate effort and approve earnings.", "/work")}{Platform.OS === "web" && <><View style={styles.itemDivider} />{item("add-to-home-screen", "#176B73", "#E4F1F0", "Install on iPhone", "Add this web app to your Safari home screen.", "/install")}</>}<View style={styles.itemDivider} />{item("manage-accounts", "#7761B8", "#F1ECFA", "Family settings", "Understand who is included on this device.", "/settings")}</View><View style={styles.note}><MaterialIcons name="lock" size={18} color="#65737C" /><Text style={styles.noteText}>This version keeps your family’s money record privately on this device.</Text></View></View></ScreenContainer>; }
const styles = StyleSheet.create({ content: { flex: 1, padding: 20, paddingTop: 16 }, eyebrow: { color: "#176B73", fontSize: 11, letterSpacing: 1.3, fontWeight: "800" }, title: { color: "#1D2C3A", fontSize: 28, fontWeight: "800", marginTop: 3 }, subtitle: { color: "#65737C", fontSize: 14, lineHeight: 20, marginTop: 6, maxWidth: 310 }, group: { marginTop: 27, borderWidth: 1, borderColor: "#E6E4DD", backgroundColor: "#FFFFFF", borderRadius: 21, overflow: "hidden" }, item: { minHeight: 84, flexDirection: "row", alignItems: "center", gap: 12, paddingHorizontal: 15, paddingVertical: 14 }, itemIcon: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14 }, itemCopy: { flex: 1, gap: 3 }, itemTitle: { color: "#1D2C3A", fontSize: 15, fontWeight: "800" }, itemText: { color: "#6F7B83", fontSize: 12, lineHeight: 16 }, itemDivider: { height: 1, backgroundColor: "#ECEBE6", marginLeft: 69 }, note: { flexDirection: "row", alignItems: "flex-start", gap: 10, borderRadius: 17, backgroundColor: "#EEEFEA", padding: 15, marginTop: 18 }, noteText: { color: "#59676E", flex: 1, fontSize: 12, lineHeight: 18 } });

